name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./assignoperation/pom.xml
          mvn clean package -f ./standardmanagement/pom.xml

      - name: Docker Build and push for Assignoperation
        uses: docker/build-push-action@v4
        with:
          context: ./assignoperation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/assignoperation:latest
            ghcr.io/${{ github.repository }}/assignoperation:${{ github.ref_name }}
            
      - name: Docker Build and push for Standardmanagement
        uses: docker/build-push-action@v4
        with:
          context: ./standardmanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/standardmanagement:latest
            ghcr.io/${{ github.repository }}/standardmanagement:${{ github.ref_name }}
            
